{% set name = "koolstof" %}
{% set version = "1.0.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/koolstof/koolstof-{{ version }}.tar.gz
  sha256: 80ffedd2980798584c0cad8d07b2d2de76734172685dc19c560ce90d0e92a5e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pandas
    - scipy

test:
  imports:
    - koolstof
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Processing measurements of dissolved inorganic carbon
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/koolstof

extra:
  recipe-maintainers:
    - mvdh7
