{% set name = "koolstof" %}
{% set version = "1.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/koolstof-{{ version }}.tar.gz
  sha256: ca7dd159b7ca9998930b366f1f64db0a9ccd9fcbfe2fb1aa0d0eb8b23679e1c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pandas
    - scipy

test:
  imports:
    - koolstof
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Processing measurements of dissolved inorganic carbon
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/koolstof

extra:
  recipe-maintainers:
    - mvdh7
